# Generated by Django 2.0.7 on 2018-07-09 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180709_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingdata',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
