# Generated by Django 2.0.7 on 2018-07-09 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_parkingdata_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingdata',
            old_name='location',
            new_name='staticDataUrl',
        ),
        migrations.AddField(
            model_name='parkingdata',
            name='dynamicDataUrl',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='parkingdata',
            name='limitedAccess',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingdata',
            name='uuid',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
