# Generated by Django 2.0.7 on 2018-07-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180709_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingdata',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='parkingdata',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='parkingdata',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='parkingdata',
            name='limitedAccess',
            field=models.BooleanField(max_length=6),
        ),
    ]
