# Generated by Django 2.0.7 on 2018-07-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180710_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingdata',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
