# Generated by Django 2.0.7 on 2018-07-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180710_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingdata',
            old_name='location',
            new_name='geoLocation',
        ),
    ]
