# Generated by Django 2.0.7 on 2018-07-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180710_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingdata',
            name='dynamicDataUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parkingdata',
            name='geoLocation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
