# Generated by Django 2.0.7 on 2018-07-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180710_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingdata',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
