# Generated by Django 2.0.7 on 2018-07-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_parkingdata_facilitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingdata',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parkingdata',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='parkingdata',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
