# Generated by Django 2.0.7 on 2018-07-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180712_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingdata',
            name='region',
            field=models.CharField(blank=True, default='default', max_length=255, null=True),
        ),
    ]
