# Generated by Django 2.0.7 on 2018-07-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_parkingdata_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingdata',
            name='staticData',
            field=models.TextField(blank=True, null=True),
        ),
    ]
