# Generated by Django 2.0.7 on 2018-07-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_parkingdata_staticdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingdata',
            name='staticData',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
