# Generated by Django 2.0.7 on 2018-07-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180716_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingdata',
            name='staticData',
            field=models.TextField(blank=True, null=True),
        ),
    ]
