# Generated by Django 2.0.7 on 2018-07-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180716_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingdata',
            name='mark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
