# Generated by Django 2.0.7 on 2018-07-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_parkingdata_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingdata',
            name='usage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
