# Generated by Django 2.0.7 on 2018-07-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20180723_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingdata',
            name='facilityType',
        ),
    ]
