# Generated by Django 2.0.7 on 2018-07-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_parkingdata_facilitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingdata',
            name='accessPoints',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingdata',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingdata',
            name='contactPersons',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingdata',
            name='minimumHeightInMeters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingdata',
            name='openingTimes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingdata',
            name='tariffs',
            field=models.BooleanField(default=False),
        ),
    ]
