# Generated by Django 2.0.7 on 2018-07-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20180723_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingdata',
            name='staticData',
        ),
    ]
